title: Eventya Dev Docs
description: Our toolbox to create awesomen web and mobile appls using Rails, Hotwire and Tailwind
baseurl: "" # Keep this blank for GitHub Pages
url: https://eventya.github.io/docs



