title: Eventya Dev Docs
description: Our toolbox to create awesomen web and mobile appls using Rails, Hotwire and Tailwind
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
